heightmap:
  filename: heightmap.png
  scale: 0.0
respawn_loc:
  pitch: 0
  roll: 0
  x: 500.0
  y: 10.0
  yaw: 0
  z: 500.0
sensors:
  camera: true
  imu: true
  lidar: true
  pose: true
timescale: 50.0
track_info:
  bush_demarcation: 0.0
  centerline_file: interpolated_traj.csv
  obs_density: 0.0
  offtrack_roughness: 0.0
  ox: 200.0
  oy: 200.0
  scale: 1.0
  texture_blend_factor: 0.9
  track_width: 5.0
  vegetation_density: 0.0
vehicle_params:
  Bf: 10.0
  Br: 10.0
  Cf: 1.0
  Cr: 1.0
  I: 300.0
  K_aero: 3.0
  K_brake: 1644.2613557021652
  K_cmd: 1756.5701183561132
  K_friction: 30.0
  K_steer: 1.0
  K_v: 50.0
  Lf: 1.0
  Lr: 1.0
  delay: 0
  g: 9.81
  h_cg: 0.0
  m: 250.0
  max_steer: 0.34
  mu_f: 0.8069050090923404
  mu_r: 0.9534534908014838
  v_kin: 3.0
